# Generated by Django 3.1.7 on 2021-03-26 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTeacherData',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3ddb29b1-c3b7-48f3-a7d8-ba634fe5e3f9'), primary_key=True, serialize=False, unique=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('password_state', models.BooleanField(default=True)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collegeteacherdata')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
