# Generated by Django 3.1.7 on 2021-03-26 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('537648f7-e8fd-4ea9-8e3c-6d11bb242fc8'), primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('cisco_id', models.TextField(blank=True, null=True)),
                ('room_id', models.TextField(blank=True, null=True)),
                ('meeting_id', models.TextField(blank=True, null=True)),
                ('meeting_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('330951d4-0a18-4ce3-811e-4e4cd0e73f65'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('class_year', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('cisco_id', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('33fb704f-7441-4b62-b5f1-2e2ad004ae3a'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cisco_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b28b13c5-df5e-486f-b19d-856251963a31'), primary_key=True, serialize=False, unique=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
